// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package web

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebsrvClient is the client API for Websrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebsrvClient interface {
	//用户注册
	Registory(ctx context.Context, in *RegistoryReq, opts ...grpc.CallOption) (*RegistoryReply, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
}

type websrvClient struct {
	cc grpc.ClientConnInterface
}

func NewWebsrvClient(cc grpc.ClientConnInterface) WebsrvClient {
	return &websrvClient{cc}
}

func (c *websrvClient) Registory(ctx context.Context, in *RegistoryReq, opts ...grpc.CallOption) (*RegistoryReply, error) {
	out := new(RegistoryReply)
	err := c.cc.Invoke(ctx, "/T.srv.web.api.websrv/Registory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websrvClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/T.srv.web.api.websrv/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsrvServer is the server API for Websrv service.
// All implementations must embed UnimplementedWebsrvServer
// for forward compatibility
type WebsrvServer interface {
	//用户注册
	Registory(context.Context, *RegistoryReq) (*RegistoryReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	mustEmbedUnimplementedWebsrvServer()
}

// UnimplementedWebsrvServer must be embedded to have forward compatible implementations.
type UnimplementedWebsrvServer struct {
}

func (UnimplementedWebsrvServer) Registory(context.Context, *RegistoryReq) (*RegistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registory not implemented")
}
func (UnimplementedWebsrvServer) Login(context.Context, *LoginReq) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedWebsrvServer) mustEmbedUnimplementedWebsrvServer() {}

// UnsafeWebsrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebsrvServer will
// result in compilation errors.
type UnsafeWebsrvServer interface {
	mustEmbedUnimplementedWebsrvServer()
}

func RegisterWebsrvServer(s grpc.ServiceRegistrar, srv WebsrvServer) {
	s.RegisterService(&Websrv_ServiceDesc, srv)
}

func _Websrv_Registory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsrvServer).Registory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/T.srv.web.api.websrv/Registory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsrvServer).Registory(ctx, req.(*RegistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websrv_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsrvServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/T.srv.web.api.websrv/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsrvServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Websrv_ServiceDesc is the grpc.ServiceDesc for Websrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Websrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "T.srv.web.api.websrv",
	HandlerType: (*WebsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registory",
			Handler:    _Websrv_Registory_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Websrv_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/web.proto",
}
