// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package web

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type WebsrvHTTPServer interface {
	Login(context.Context, *LoginReq) (*LoginReply, error)
	Registory(context.Context, *RegistoryReq) (*RegistoryReply, error)
}

func RegisterWebsrvHTTPServer(s *http.Server, srv WebsrvHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/web/registory", _Websrv_Registory0_HTTP_Handler(srv))
	r.POST("/v1/web/login", _Websrv_Login0_HTTP_Handler(srv))
}

func _Websrv_Registory0_HTTP_Handler(srv WebsrvHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegistoryReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/T.srv.web.api.websrv/Registory")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Registory(ctx, req.(*RegistoryReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegistoryReply)
		return ctx.Result(200, reply)
	}
}

func _Websrv_Login0_HTTP_Handler(srv WebsrvHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/T.srv.web.api.websrv/Login")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

type WebsrvHTTPClient interface {
	Login(ctx context.Context, req *LoginReq, opts ...http.CallOption) (rsp *LoginReply, err error)
	Registory(ctx context.Context, req *RegistoryReq, opts ...http.CallOption) (rsp *RegistoryReply, err error)
}

type WebsrvHTTPClientImpl struct {
	cc *http.Client
}

func NewWebsrvHTTPClient(client *http.Client) WebsrvHTTPClient {
	return &WebsrvHTTPClientImpl{client}
}

func (c *WebsrvHTTPClientImpl) Login(ctx context.Context, in *LoginReq, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/web/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/T.srv.web.api.websrv/Login"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WebsrvHTTPClientImpl) Registory(ctx context.Context, in *RegistoryReq, opts ...http.CallOption) (*RegistoryReply, error) {
	var out RegistoryReply
	pattern := "/v1/web/registory"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/T.srv.web.api.websrv/Registory"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
